### ISSUE TITLE
缓存失效的时候，当前进程会挂起，是怎么回事？

### ISSUE THREAD

**Issue by lemos1235** [gookit/cache#15]
我在使用基于内存的那个缓存，发现当缓存失效的时候，当前进程会挂起，怎么回事？

**Comment by lemos1235** [comment]
发现过期后进入 Del 函数造成加锁两次，导致当前线程一直被阻塞。

**Comment by inhere** [comment]
L57 这里吗。 检查代码好像发现这里该用内部的 `del()` 方法

https://github.com/gookit/cache/blob/5e0b1084ddb2de3a45f1f1c84909860131b8f679/driver_memory.go#L49-L61
